// Todos los textos de la interfaz (francés). Un solo sitio para poder añadir otro idioma más adelante.
// Botones: verbo primero, sin mayúsculas de título ni exclamaciones (Design System).

export const t = {
  marque: 'Debajah Création',
  app: 'Mon Stand',

  onglets: { caisse: 'Caisse', stock: 'Stock', heures: 'Heures', cloture: 'Clôture' },

  commun: {
    annuler: 'Annuler',
    fermer: 'Fermer',
    enregistrer: 'Enregistrer',
    supprimer: 'Supprimer',
    modifier: 'Modifier',
    retour: 'Retour',
    valider: 'Valider',
    ok: 'OK',
    oui: 'Oui',
    non: 'Non',
    rechercher: 'Rechercher',
    aucunResultat: 'Aucun résultat',
    champRequis: 'Champ requis',
    montantInvalide: 'Montant invalide',
    plusTard: 'Pas maintenant',
    chargement: 'Chargement…',
    aujourdhui: "Aujourd'hui",
    total: 'Total',
    remise: 'Remise',
    sousTotal: 'Sous-total',
  },

  sync: {
    enLigne: 'En ligne',
    horsLigne: 'Hors ligne',
    synchro: 'Synchronisation…',
    erreur: 'Erreur de synchronisation',
    enAttente: (n: number) => (n === 1 ? '1 en attente' : `${n} en attente`),
    bandeauHorsLigne: 'Hors ligne : les ventes sont gardées sur ce téléphone et partiront dès le retour du réseau.',
    bandeauErreur: (detail: string) => `Synchronisation en erreur : ${detail}`,
    revoque: 'Appareil révoqué',
  },

  acces: {
    titre: 'Qui vend aujourd’hui ?',
    choisir: 'Choisissez votre prénom',
    saisirPin: (prenom: string) => `PIN de ${prenom}`,
    pinIncorrect: 'Code incorrect',
    essaisRestants: (n: number) => (n === 1 ? 'Il reste 1 essai.' : `Il reste ${n} essais.`),
    bloque: 'Trop d’essais. Réessayez dans une minute.',
    changerVendeuse: 'Changer de vendeuse',
    aucuneVendeuse: 'Aucune vendeuse. Ajoutez-en une dans les réglages.',
  },

  journee: {
    ouvrir: 'Ouvrir la journée',
    titreOuvrir: 'Nouvelle journée',
    lieu: 'Lieu du marché',
    fonds: 'Fond de caisse',
    fondsAide: 'Ce que contient la caisse au départ, par devise.',
    ouverteDepuis: (heure: string) => `Ouverte à ${heure}`,
    aucuneOuverte: 'Aucune journée ouverte',
    aucuneOuverteAide: 'Ouvrez la journée pour commencer à vendre.',
    dejaCloturee: 'La journée est clôturée. Ouvrez-en une nouvelle pour vendre.',
    commencerHeures: 'Commencer mes heures',
    commencerHeuresAide: (heure: string) => `Début à ${heure}, arrondi à la demi-heure.`,
    heuresNonTerminees: (date: string, heure: string) => `Heures du ${date} (${heure}) jamais terminées`,
    heuresNonTermineesAide:
      'Dans l’onglet Heures : terminez-les, corrigez l’heure de fin, puis commencez celles du jour.',
    ouverte: 'Journée ouverte',
    ouverteEtHeures: (heure: string) => `Journée ouverte · en service depuis ${heure}`,
  },

  caisse: {
    tout: 'Tout',
    rechercherArticle: 'Rechercher un article',
    panier: 'Panier',
    panierVide: 'Panier vide',
    panierVideAide: 'Touchez un article pour l’ajouter.',
    articles: (n: number) => (n === 1 ? '1 article' : `${n} articles`),
    encaisser: 'Encaisser',
    voirPanier: 'Voir le panier',
    viderPanier: 'Vider le panier',
    remisePanier: 'Remise sur le panier',
    remiseAide: 'En CFP, déduite du total.',
    ajouterRemise: 'Ajouter une remise',
    retirerRemise: 'Retirer la remise',
    stockEpuise: 'Stock épuisé',
    stockInsuffisant: 'Stock insuffisant',
    promo: (pct: number, n: number) => `−${pct} % sur ${n} unité${n > 1 ? 's' : ''}`,
    promoTag: (pct: number) => `2ᵉ à −${pct} %`,
    ajoute: (nom: string) => `${nom} ajouté`,
  },

  cobro: {
    titre: 'Encaisser',
    aPayer: 'À payer',
    resteAPayer: 'Reste à payer',
    modePaiement: 'Comment paie le client ?',
    carte: 'Carte',
    recu: 'Montant reçu',
    compteJuste: 'Compte juste',
    autreMontant: 'Autre montant',
    aRendre: 'À rendre',
    rienARendre: 'Rien à rendre',
    manque: 'Il manque',
    remiseEncaissement: 'Remise à l’encaissement',
    payerResteAutrement: 'Payer le reste autrement',
    validerVente: 'Valider la vente',
    venteEnregistree: 'Vente enregistrée',
    venteAnnulee: 'Vente annulée',
    annulerVente: 'Annuler',
    taux: (devise: string, taux: string) => `1 ${devise} = ${taux} CFP`,
    equivalent: '≈',
    paiementsSaisis: 'Paiements',
    retirerPaiement: 'Retirer ce paiement',
    sansTaux: 'Pas de taux pour cette devise',
  },

  stock: {
    titre: 'Stock',
    modeVente: 'Consulter',
    modeEdition: 'Ajuster',
    epuise: 'Épuisé',
    faible: 'Faible',
    prixAFixer: 'Prix à fixer',
    nouvelArticle: 'Nouvel article',
    ficheArticle: 'Article',
    nom: 'Nom',
    categorie: 'Catégorie',
    emoji: 'Emoji',
    prixCfp: 'Prix (CFP)',
    promo2eme: '2ᵉ unité à −… %',
    promoAide: 'Vide = pas de promo.',
    prixDevises: 'Prix en devise',
    prixDevisesAide: 'Vide = calculé depuis le prix CFP au taux du jour.',
    calcule: 'calculé',
    manuel: 'fixé',
    quantite: 'Quantité en stock',
    reassort: 'Réassort',
    ajustement: 'Ajustement',
    inventaire: 'Inventaire',
    motif: 'Motif',
    desactiver: 'Retirer de la vente',
    reactiver: 'Remettre en vente',
    inactif: 'Retiré',
    enregistre: 'Article enregistré',
    mouvementEnregistre: (delta: number) => (delta > 0 ? `+${delta} en stock` : `${delta} en stock`),
    epuises: (n: number) => `Épuisés (${n})`,
    faibles: (n: number) => `Faible (${n})`,
    stockOk: 'Stock disponible',
  },

  heures: {
    titre: 'Heures',
    commencer: 'Commencer',
    terminer: 'Terminer',
    maintenir: 'Maintenir pour confirmer',
    enServiceDepuis: (heure: string) => `En service depuis ${heure}`,
    nonPointee: 'Pas en service',
    arrondi: 'Arrondi à la demi-heure.',
    ceMois: 'Ce mois',
    total: 'Total',
    aPayer: 'À payer',
    paye: 'Payé',
    sessions: 'Sessions',
    aucuneSession: 'Aucune session',
    ajouter: 'Ajouter une session',
    modifierSession: 'Modifier la session',
    date: 'Date',
    debut: 'Début',
    fin: 'Fin',
    commentaire: 'Commentaire',
    finAvantDebut: 'La fin doit être après le début.',
    payee: 'Payée',
    nonPayee: 'À payer',
    marquerPayee: 'Marquer payée',
    marquerNonPayee: 'Marquer à payer',
    supprimerConfirm: 'Supprimer cette session ?',
    enCours: 'en cours',
    sessionEnregistree: 'Session enregistrée',
    tauxHoraire: 'Taux horaire',
  },

  cloture: {
    titre: 'Clôture',
    ventes: 'Ventes',
    chiffreAffaires: 'Chiffre d’affaires',
    panierMoyen: 'Panier moyen',
    articlesVendus: 'Articles vendus',
    remisesPanier: 'Remises panier',
    remisesEncaissement: 'Remises à l’encaissement',
    parPaiement: 'Encaissements',
    topArticles: 'Meilleures ventes',
    stock: 'Stock',
    aucuneVente: 'Aucune vente aujourd’hui',
    ventesDuJour: 'Ventes du jour',
    compterCaisse: 'Compter la caisse',
    comptage: 'Comptage de caisse',
    attendu: 'Attendu',
    compte: 'Compté',
    ecart: 'Écart',
    juste: 'Juste',
    fond: 'Fond',
    recu: 'Reçu',
    rendu: 'Rendu',
    commentaire: 'Commentaire de clôture',
    cloturer: 'Clôturer la journée',
    cloturerAide: 'La journée passe dans l’historique. Les ventes ne pourront plus être annulées.',
    journeeCloturee: 'Journée clôturée',
    heuresEnCours: (heure: string) => `Vos heures tournent encore (depuis ${heure})`,
    heuresEnCoursAide:
      'Pensez à les terminer dans l’onglet Heures. En cas d’oubli, touchez ensuite la session pour corriger l’heure de fin.',
    rappelHeures: 'Pensez à terminer vos heures dans l’onglet Heures.',
    historique: 'Historique',
    aucunHistorique: 'Aucune journée clôturée',
    detailJournee: 'Journée',
    cloturee: (heure: string) => `clôturée à ${heure}`,
    annulee: 'annulée',
    monnaie: 'monnaie',
    pdf: 'PDF',
  },

  reglages: {
    titre: 'Réglages',
    vendeuses: 'Vendeuses',
    ajouterVendeuse: 'Ajouter une vendeuse',
    prenom: 'Prénom',
    pin: 'PIN (4 chiffres)',
    nouveauPin: 'Nouveau PIN',
    confirmerPin: 'Confirmer le PIN',
    pinDifferent: 'Les deux PIN ne correspondent pas.',
    pinFormat: 'Le PIN fait 4 chiffres.',
    pinModifie: 'PIN modifié',
    changerPin: 'Changer le PIN',
    taux: 'Taux de change',
    tauxAide: 'CFP pour 1 unité. L’euro est fixe (parité).',
    tauxSource: (source: string, date: string) => `${source} · ${date}`,
    categories: 'Catégories',
    ajouterCategorie: 'Ajouter une catégorie',
    theme: 'Apparence',
    themeAuto: 'Automatique',
    themeClair: 'Plein soleil',
    themeSombre: 'Soir',
    appareil: 'Cet appareil',
    exporter: 'Exporter les données (JSON)',
    exporte: 'Export prêt',
    version: 'Version',
    installer: 'Installer l’app',
    installerTitre: 'Mon Stand sur l’écran d’accueil',
    installerAide: 'Installée, l’app s’ouvre en plein écran et garde ses données même sans réseau.',
    installerIos: 'Sur iPhone : Partager, puis « Sur l’écran d’accueil ».',
    installerAutre: 'Ouvrez ce lien dans Safari ou Chrome pour installer l’app.',
    copierLien: 'Copier le lien',
    lienCopie: 'Lien copié',
    dejaInstallee: 'App installée',
    lieuDefaut: 'Lieu par défaut',
    enregistre: 'Réglage enregistré',
  },

  appairage: {
    titre: 'Appairer ce téléphone',
    aide: 'Le code s’obtient dans le panneau du propriétaire (/admin). Il est valable 15 minutes.',
    code: 'Code d’appairage',
    codeFormat: 'Le code fait 8 caractères.',
    codeInvalide: 'Code inconnu, déjà utilisé ou expiré.',
    horsLigne: 'Pas de réseau : l’appairage a besoin d’une connexion.',
    bootstrapEchoue: 'Les données n’ont pas pu être chargées. Demandez un nouveau code et réessayez.',
    nom: 'Nom de cet appareil',
    nomDefaut: 'Téléphone du stand',
    valider: 'Appairer',
    revoque: 'Cet appareil a été révoqué. Demandez un nouveau code au propriétaire.',
    desappairer: 'Désappairer cet appareil',
    desappairerAide:
      'Efface les données locales de ce téléphone. Impossible tant qu’il reste des actions à synchroniser.',
    appareilNom: (nom: string) => `Appareil : ${nom}`,
    derniereSync: (quand: string) => `Dernière synchronisation ${quand}`,
    jamaisSync: 'Jamais synchronisé',
    resynchroniser: 'Synchroniser maintenant',
  },

  admin: {
    titre: 'Panneau du propriétaire',
    jeton: 'Jeton d’administration',
    jetonAide: 'Sans Cloudflare Access, collez le jeton ADMIN_TOKEN défini sur le Worker. Il reste dans cet onglet.',
    nonConfigure: 'Administration non configurée sur le serveur (Cloudflare Access ou ADMIN_TOKEN).',
    appairage: 'Appairer un téléphone',
    appairageAide: 'Générez un code, puis saisissez-le sur le téléphone à l’ouverture de l’app.',
    genererCode: 'Générer un code',
    codeValable: (heure: string) => `Valable jusqu’à ${heure}`,
    appareils: 'Appareils',
    aucunAppareil: 'Aucun appareil appairé.',
    actualiser: 'Actualiser',
    appaire: 'Appairé le',
    vu: 'vu le',
    actif: 'Actif',
    revoque: 'Révoqué',
    revoquer: 'Révoquer',
    revoquerConfirm: (nom: string) => `Révoquer « ${nom} » ? Il devra être appairé de nouveau.`,
  },

  panneau: {
    onglets: {
      kpis: 'Ventes',
      journees: 'Journées',
      heures: 'Heures',
      exports: 'Exports',
      taux: 'Taux',
      appareils: 'Appareils',
    },
    mois: 'Mois',
    chiffreAffaires: 'Chiffre d’affaires',
    journees: 'Journées',
    ventes: 'Ventes',
    panierMoyen: 'Panier moyen',
    articlesVendus: 'Articles vendus',
    parLieu: 'Par marché',
    parPaiement: 'Encaissements',
    topArticles: 'Meilleures ventes',
    aucuneJournee: 'Aucune journée ce mois-ci.',
    date: 'Date',
    lieu: 'Lieu',
    vendeuse: 'Vendeuse',
    nbVentes: 'Ventes',
    encaisse: 'Encaissé',
    cloture: 'Clôture',
    voirPdf: 'Voir le PDF',
    voirHtml: 'Voir la clôture',
    regenerer: 'Régénérer',
    pasDeCloture: 'Pas encore archivée',
    ouverte: 'Ouverte',
    heuresTitre: 'Heures du mois',
    total: 'Total',
    aPayer: 'À payer',
    paye: 'Payé',
    tauxHoraire: 'Taux horaire',
    exportVentes: 'Ventes du mois (CSV)',
    exportHeures: 'Heures du mois (CSV)',
    exportAide: 'Fichiers CSV (séparateur « ; ») qui s’ouvrent directement dans Excel.',
    archives: 'Archives mensuelles',
    archivesAide:
      'Copie complète de la base en JSON dans R2, le 1er de chaque mois. D1 Time Travel couvre les 30 derniers jours.',
    archiverMaintenant: 'Archiver le mois dernier maintenant',
    aucuneArchive: 'Aucune archive.',
    tauxTitre: 'Taux de change',
    tauxAide:
      'Mis à jour chaque matin à 6 h (BCE, 1 € = 119,332 CFP). Les téléphones les reçoivent à la synchronisation suivante.',
    tauxSource: (source: string, date: string) => `Source ${source} · ${date}`,
    actualiserTaux: 'Actualiser maintenant',
    tauxActualises: 'Taux actualisés',
    chargement: 'Chargement…',
  },

  erreurs: {
    generique: 'Une erreur est survenue. Réessayez.',
  },
} as const;

export type Textes = typeof t;
